"""create tenders table

Hand-written, not autogenerated: Alembic does not detect
`GENERATED ALWAYS AS ... STORED` columns, so total_amount has to be declared
here explicitly. See DATABASE_SCHEMA.md 5.

Revision ID: 9c5581b01a80
Revises: 100ea7412eea
Create Date: 2026-08-30 19:22:41.905612

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c5581b01a80"
down_revision: str | Sequence[str] | None = "100ea7412eea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # tender_name_id is ON DELETE RESTRICT: a tender name in use cannot be
    # deleted, admins deactivate it instead (DATABASE_SCHEMA.md 2).
    op.execute(
        """
        create table tenders (
          id                  uuid primary key default uuid_generate_v4(),
          client_id           uuid not null references clients (id) on delete cascade,
          tender_name_id      uuid not null references tender_names (id) on delete restrict,
          quantity            integer not null check (quantity > 0),
          price               numeric(12,2) not null check (price >= 0),
          total_amount        numeric(14,2) generated always as (quantity * price) stored,
          status              tender_status not null default 'Pending',
          created_by          uuid references users (id) on delete set null,
          created_at          timestamptz not null default now(),
          updated_at          timestamptz not null default now()
        )
        """
    )
    op.execute("create index idx_tenders_client_id on tenders (client_id)")
    op.execute("create index idx_tenders_status on tenders (status)")
    op.execute("create index idx_tenders_created_by on tenders (created_by)")
    op.execute(
        "create trigger trg_tenders_updated_at before update on tenders "
        "for each row execute function set_updated_at()"
    )
    # See DATABASE_SCHEMA.md 3 — RLS on with no policies blocks Supabase's
    # PostgREST surface; app authorization stays in the FastAPI service layer.
    op.execute("alter table tenders enable row level security")


def downgrade() -> None:
    op.execute("drop table if exists tenders")
